// End-to-end replay with no camera and no MediaPipe: feed a recorded frame
// timeline through the real calibration and morph maths and check what comes
// out the far end.
//
// Run: npx tsx tests/calibration_replay_test.ts
//
// The fixture is regenerated by tests/make_calibration_fixture.ts. It is
// currently synthetic (its `source` field says so) — swap in a real
// FaceMorphProcessor.sample() dump of the same shape and this test needs no
// changes.

import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import {
  TalkingDetector,
  buildCalibrationProfile,
  cappedAlpha,
  geometricLevel,
  normalizedLevel,
  summarizePhase,
  validatePhase,
  type CalibrationFrame,
} from '../renderer/lib/calibration'
import type { CalibrationPhase, CalibrationPhaseSummary } from '../main/protocol'

interface FixtureFrame extends CalibrationFrame {
  segment: string
  micRms: number
}

const fixture = JSON.parse(
  fs.readFileSync(path.join(import.meta.dirname, 'fixtures', 'calibration_frames.json'), 'utf-8'),
) as { source: string; frames: FixtureFrame[] }

const bySegment = (label: string) => fixture.frames.filter((f) => f.segment === label)

// ---- Replay the four calibration phases ----

const phases: Partial<Record<CalibrationPhase, CalibrationPhaseSummary>> = {}
const neutral = validatePhase(summarizePhase('neutral', bySegment('neutral')))
phases.neutral = neutral
for (const phase of ['smileClosed', 'smileOpen', 'frown'] as const) {
  phases[phase] = validatePhase(summarizePhase(phase, bySegment(phase)), neutral)
}

for (const [phase, summary] of Object.entries(phases)) {
  assert.equal(summary!.status, 'ok', `${phase} should pass on a clean run: ${summary!.qualityFlags}`)
  assert.ok(summary!.frames > 60, `${phase} recorded enough frames`)
  assert.equal(summary!.faceVisibleRatio, 1, `${phase} kept the face in view`)
}

const profile = buildCalibrationProfile(phases, {
  participantId: 'replay',
  dyadId: '',
  studyId: '',
  seat: 'P1',
  appVersion: 'test',
  camera: { width: 1280, height: 720 },
})
assert.ok(profile, 'a clean replayed run produces a profile')

// The measured gain has to be a plausible mouth movement, not a rounding artefact.
assert.ok(
  profile!.derived.smile.cornerTravel > 0.04 && profile!.derived.smile.cornerTravel < 0.2,
  `smile travel should be plausible, got ${profile!.derived.smile.cornerTravel}`,
)
assert.ok(
  profile!.derived.frown.cornerTravel > 0.04,
  `frown travel should be plausible, got ${profile!.derived.frown.cornerTravel}`,
)
assert.ok(
  profile!.derived.jawCoupling > 0,
  'the open-mouth phase should reveal some jaw-to-corner coupling',
)

// ---- Replay the detection timeline ----

const smileRange = profile!.derived.smile.range
const frownRange = profile!.derived.frown.range
const neutralSmile = neutral.scores.smile.mean
const neutralFrown = neutral.scores.frown.mean

function labelFor(frame: FixtureFrame, talking: boolean): 'neutral' | 'smiling' | 'frowning' {
  const smileLevel = normalizedLevel(frame.scores.smile, neutralSmile, smileRange)
  const frownLevel = normalizedLevel(frame.scores.frown, neutralFrown, frownRange)
  const smileBar = profile!.derived.smile.deadZone * (talking ? 1.5 : 1)
  const frownBar = profile!.derived.frown.deadZone
  const smiling = smileLevel >= smileBar
  // Frowns are suppressed while talking: speech drives the same pout features.
  const frowning = !talking && frownLevel >= frownBar
  if (smiling && frowning) return smileLevel - smileBar >= frownLevel - frownBar ? 'smiling' : 'frowning'
  if (smiling) return 'smiling'
  if (frowning) return 'frowning'
  return 'neutral'
}

const detector = new TalkingDetector(profile!.derived.talking.openRatioStdNeutral)
const labels = new Map<string, Set<string>>()
const talkingBySegment = new Map<string, number>()

for (const frame of fixture.frames) {
  const talking = detector.push(frame.tsMs, frame.geometry.mouthOpenRatio, frame.micRms)
  const label = labelFor(frame, talking)
  if (!labels.has(frame.segment)) labels.set(frame.segment, new Set())
  labels.get(frame.segment)!.add(label)
  if (talking) talkingBySegment.set(frame.segment, (talkingBySegment.get(frame.segment) ?? 0) + 1)
}

assert.ok(labels.get('smileClosed')!.has('smiling'), 'the closed-mouth smile is detected as a smile')
assert.ok(labels.get('smileOpen')!.has('smiling'), 'the open-mouth smile is detected as a smile')
assert.ok(labels.get('frown')!.has('frowning'), 'the frown is detected as a frown')
assert.ok(!labels.get('neutral')!.has('smiling'), 'a relaxed face is not a smile')
assert.ok(!labels.get('neutral')!.has('frowning'), 'a relaxed face is not a frown')

// ---- Talking ----

assert.ok(
  (talkingBySegment.get('talking') ?? 0) > bySegment('talking').length * 0.5,
  'speech is detected for most of the talking stretch',
)
for (const quiet of ['neutral', 'smileClosed', 'smileOpen', 'frown']) {
  assert.equal(
    talkingBySegment.get(quiet) ?? 0,
    0,
    `${quiet} is a held expression, not speech`,
  )
}
assert.ok(
  !labels.get('talking')!.has('frowning'),
  'talking must never be reported as a frown — that is the false positive this replaces',
)

// ---- The total cap over the whole timeline ----

for (const frame of fixture.frames) {
  for (const commanded of [0.2, 0.5, 1]) {
    const level = geometricLevel(profile, frame.geometry, 'smile')
    const applied = cappedAlpha(commanded, level)
    assert.ok(
      level + Math.abs(applied) <= 1 + 1e-9,
      `frame ${frame.tsMs}ms: real expression + morph exceeded their maximum`,
    )
    assert.ok(Math.abs(applied) <= commanded + 1e-9, 'the cap only ever reduces the command')
  }
}

// At the height of the real smile there should be visibly less budget than at rest.
const peakSmileFrame = bySegment('smileClosed').reduce((best, f) =>
  f.scores.smile > best.scores.smile ? f : best,
)
const restFrame = bySegment('neutral')[45]
assert.ok(
  geometricLevel(profile, peakSmileFrame.geometry, 'smile') >
    geometricLevel(profile, restFrame.geometry, 'smile') + 0.3,
  'a real smile should eat a real share of the morph budget',
)

console.log(`calibration replay checks passed (${fixture.frames.length} ${fixture.source} frames)`)
